services:
  employee-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    image: employee-api:v1.0.0
    container_name: employee-api
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge
